version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www
    expose:
      - "9000"  # Se expone internamente
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8000:80"  # Se accede a la aplicación en http://localhost:8000
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: challenge-database
      MYSQL_ROOT_PASSWORD: challenge-backend
    ports:
      - "3304:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
